index.js
This patch makes the server bind to the hostname given in the config option `host` if it is set; if `host` is not set, the behavior is unchanged and the server listens on a wildcard address.
=> Listen on configured hostname

index.js, test/app-key.js
this change allows the appkey to be set as a per-instance configuration option.
this will enable testnet instances which will never connect to the main net.
(the appkey is a part of secret handshake, and if two peers do not have the same appkey they will not be able to successfully establish a connection) This means we can easily run a testnet without much fuss, and people developing new things on top of ssb don't need to worry about pushing nonsense to something humans are using.
=> support testnets

index.js
When running behind a NAT, listening on opts.host will point to an external ip, and not a local network interface, causing a stacktrace. 
Closes https://github.com/ssbc/scuttlebot/issues/296
=> Don't listen on opts.host

index.js, package.json, test/local.js
My sbot started shutting off periodically. I am running it with ssb-party and patchfoo. I found that patchfoo's rpc connection was getting closed by scuttlebot, and then ssb-party would shut down scuttlebot since there were no more clients connected. This PR restores the earlier behavior, from before b659eecf3512660c786bac707b54b0c10107a68a, of allowing clients to remain connected indefinitely. Note that client connections from a master key (for example, as described in `%9id5lKdgxl3ZleJa5BeMeAVLCnMwQepyntPLxisLnBE=.sha256`) will still get closed by the inactivity timeout. To allow for those, clients will have to use a keepalive.
=> Don't timeout RPC from self for inactivity

index.js
Rebased this on top of current version as there were some conflicts with my other version.
=> Make --tor-only work with local sbot instances

index.js, package.json, plugins/net.js, plugins/shs.js, test/app-key.js, test/auth.js, test/timeout.js
this is a refactor to make the relationship of transport and transform (aka security) much cleaner.
I don't want secret-stack/index to have new network protocols added to it, it's meant to be more high level than that. I've refactored to move those into plugins - net and shs are still hardwired in, but I left them there because they had always been part of this module anyway.
This means that a sbot plugin can now be the source of new networking (transport) protocols (or new crypto protocols!)
to add a network protocol, use plugins/net as the template, basically: call `transport(createMultiserverPlugin)`, note, createMultiserverPlugin 
note: in the case of multiple crypto (transform) protocols, createMultiserverPlugin is called with an `instance` which is an integer - if there are two …
=> refactor to make protocols pluggable

index.js
When creating default incoming 'net' connection, opts.port and opts.host
where ignored. This causes ssb-client/test/index.js to fail and breaks
backward compatibility.
=> Respect opts.port and opts.host

index.js, package.json, plugins/net.js
- Let multiserver plugins decide about default values for host, port and scope.
- Make sure not to put `port: undefined` or `host: undefined` into default connection
- Make sure default outgoing net connection has the same port as default incoming
How do you feel about the usage of the `debug` module here? I find it very useful.
=> Use multiserver's default values instead of a dupicated effort

README.md, plugins.md
added `plugins.md` as a starting point for creating `secret-stack` plugins. not sure if this should be in the main readme.md or if it's ok to have it in a separate document. 
interested to know if this adds clarity or could use improvements.
see #37
=> Documentation Drive: initial plugin docs

core.js
during the documentation drive I realized that everything was using the "legacy" api in muxrpc. but the non-legacy api makes more sense and is easier to explain, so use that instead. These changes are necessary to work with that version.
=> use the non-legacy muxrpc api

api.js
This should have no breaking change in secret-stack, because it just shuffles around some if conditions in `.use(plugin)`, giving priority to some shapes of `plugin` over others.
**Before:** any function plugin, no matter if it already had `.init` attached to it, would be wrapped in an object
**After:** before wrapping the function, we first check if it already has `.init` attached to it
As a result, this solves #41 and makes it possible to use a different shape for plugins.
=> first check if function-as-plugin has .init attached to it

api.js
I wanted to make it so that ssb-minimal-pub-server loads the plugins needed for peer-invites by default, thus making it easier to configure. But found that if they had already been installed in ~/.ssb/plugins that it would just die. Seems as if it should be safe enough to just throw a warning instead of hard failing in such a case.
=> Change loading an already loaded plugin from error to warning

README.md, core.js, test/server.js
Context: when Alice initiates an RPC connection with Bob over Bluetooth (Alice is the server, Bob is the client), I needed a way for Bob to know who connected to him, and not just their `rpc.id`, but also the multiserver address.
In many cases, the multiserver address is already known and was created in each multiserver plugin, by attaching `stream.address = address` before calling `onConnection(stream)`. That's the case for these plugins: `net`, `ws`, `unix`, `bluetooth`, etc. But this information was not passed forward to the `rpc` object.
This PR attaches `.address` to the rpc object. I considered doing it on `rpc.address`, but that's actually a muxrpc call itself, as well as `rpc.getAddress` is. It seemed natural that since there is `rpc.stream`, a duplex stream with the other peer, …
=> attach multiserver address to rpc object

plugins/shs.js, test/local.js, test/seeds.js, util.js
what it says on the tin.
apparently this is a minor security win
=> convert new Buffer() to Buffer.from everywhere

package.json
=> require node.js 5.10.0 due to Buffer.from usage

src/api.ts, src/core.ts, src/index.ts, src/plugins/net.ts, src/plugins/shs.ts, src/util.ts
- Replace `any` with `unknown`
The TypeScript `any` type means that `foo: any` allows you to do `foo.x.y` and it will not emit any compilation errors. But `foo: unknown` allows you to use `foo` but **disallows** you to use `foo.x` or `foo.x.y`, e.g. you could do `console.log(foo)` but you couldn't do `console.log(foo.x)`. This is useful because `unknown` is somewhat loose (you don't have to specify **exactly** what the type of the thing is), but not too loose. `console.log(foo)` is always safe (will never crash JavaScript), but `console.log(foo.x)` **may** cause a "x is not a property of undefined" crash in JavaScript. So by sprinkling `unknown` here and there, we're progressively making the codebase safer against such runtime errors.
- Other changes I'll comment inline since they are …
=> use a few simple TypeScript features

src/core.ts, src/plugins/shs.ts, src/types.ts
Review by reading first `src/types.ts` and then the other files. Previously, config was an `any` object, which allows all kinds of objects, but also numbers, strings, undefined, etc. This PR should add some protection against typos, as well as rigorously checking against undefined and null cases possibly existing in config object.
=> add TypeScript types for the config object

package-lock.json, package.json
There's a security alert about `minimist`, which is old only for old versions of `mkdirp`. I'm pretty sure these are not used in secret-stack *other* than for devDeps and build-time scripts, but it's good to anyway update so that we explicitly have zero security issues raised.
I'll merge this if no one reviews in 48h after PR creation.
=> update mkdirp and old minimist

src/core.ts
[Manifest bootstrapping](https://github.com/ssb-js/muxrpc/#bootstrapping---automatically-loading-the-remote-manifest) has been a muxrpc feature since [Dec 2017](https://github.com/ssb-js/muxrpc/pull/37), but its usage hasn't been effectively enabled in the SSB ecosystem, and that's because [secret-stack actually just assumes the remote peer has the same manifest as the local peer](https://github.com/ssb-js/secret-stack/blob/113efba0cfba73a6eebce8aa01b18d7d6ae5f3d2/src/core.ts#L229). Anyway, this feature has been possible for others to use because secret-stack [implements](https://github.com/ssb-js/secret-stack/blob/113efba0cfba73a6eebce8aa01b18d7d6ae5f3d2/src/core.ts#L103) [it](https://github.com/ssb-js/secret-stack/blob/113efba0cfba73a6eebce8aa01b18d7d6ae5f3d2/src/core.ts#L275) as a …
=> make manifest a public muxrpc API

lib/core.js, lib/plugins/shs.js, lib/types.js, test/auth2.js
This work is motivated by PPPPP using secret-stack with new identifiers for peers based on their public key. 
Currently, secret-stack hard codes IDs `@<BASE64>.ed25519`.
I first thought about adding a special config that allows you to customize the peer ID to be whatever you want, but this was more complex to implement and also _requires_ you to configure such if you want a new ID system. That's not the _secret-stack way_, which so far has been mostly driven by plugins.
So what I went with instead is that secret-stack doesn't (or shouldn't) have a secret-stack-wide ID, but instead the *transform* plugins have the responsibility of determining the IDs. This is already true for secret handshake, because `lib/plugins/shs` is the one who sets `api.id`.
See the tests changed in this PR for a …
=> Allow transforms to set their own identifiers

lib/bare.js, package.json, test/server.js
For PPPPP we want to use secret-stack, but with [shse](https://github.com/staltz/secret-handshake-ext) instead of **shs**.
Secret-stack hardcodes `net` + `shs` and there's no way of opting out of this.
Create an alternative to index.js, `bare.js` which can be imported as `require('secret-stack/bare')` which is only the core of secret-stack *without* `net` and `shs`, so users can opt-in themselves if they want. For PPPPPP this means I can opt-in to net and **shse**.
Not a breaking change, just a new feature.
=> Support bare mode: no net, no shs

CHANGELOG.md, PLUGINS.md, README.md, lib/api.js, lib/core.js, lib/plugins/shs.js, lib/types.js, test/api.js, test/app-key.js, test/auth.js, test/auth2.js, test/close.js, test/flood.js, test/local.js, test/server.js, test/timeout.js
**An improvement to secret-stack's security and overall avoidance of spaghetti dependencies.**
This PR is a **breaking change** that allows each plugin to read `config.global` and `config[pluginName]` but nothing else.
E.g. with the config below:
```
{
global: { seed, appKey },
foo: { age: 18 },
bar: { timeout: 3000 },
qux: { path: "~/.config/app" }
}
```
A plugin named `foo` will get in its `init` function only `config.global` and `config.foo`:
```
{
name: 'foo',
manifest: {
greet: 'sync',
}
init: function init(api, config) {
// config is { global, foo }
// ...
}
}
```  
**`global`** is now a reserved word (a plugin named "global" would emit an error log and be skipped.
=> Plugins cannot read other plugin configs
